spring.datasource.url=postgres://bxmktdjavpqirb:1d11ad06993cd9156ae54ff53279346e474a7fe4ab8f5abcb9282b27e3676717@ec2-54-157-66-140.compute-1.amazonaws.com:5432/d5gv0760ct3hpd

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false